package analysis.callChainsExtractor;

import java.util.Arrays;
import java.util.HashSet;

/* System Permissions that app could not obtain
* Permission Checks can help to filter the system service interfaces that check permission at the first statement
* */
public class UnAcquirablePermissions {

    private static final String[] permissionCheckMethodSigArray = new String[]{
            // Context
            "<android.content.Context: void enforceCallingOrSelfPermission(java.lang.String,java.lang.String)>",
            "<android.content.Context: void enforceCallingPermission(java.lang.String,java.lang.String)>",
            "<android.content.Context: void enforcePermission(java.lang.String,int,int,java.lang.String)>",
            "<android.content.Context: void enforceCallingOrSelfUriPermission(android.net.Uri,int,java.lang.String)>",
            "<android.content.Context: void enforceCallingUriPermission(android.net.Uri,int,java.lang.String)>",
            "<android.content.Context: void enforceUriPermission(android.net.Uri,int,int,int,java.lang.String)>",
            "<android.content.Context: void enforceUriPermission(android.net.Uri,java.lang.String,java.lang.String,int,int,int,java.lang.String)>",
            // ...
    };
    public static HashSet<String> permissionCheckMethodSigs = new HashSet<>(Arrays.asList(permissionCheckMethodSigArray));

    private static final String[] systemPermissionArray = new String[]{
            "android.permission.MEDIA_CONTENT_CONTROL",
            "android.permission.MODIFY_ACCESSIBILITY_DATA",
            "android.permission.MANAGE_APP_OPS_RESTRICTIONS" ,
            "android.permission.RESTRICTED_VR_ACCESS",
            "android.permission.BIND_CARRIER_SERVICES",
            "android.permission.MANAGE_MEDIA_PROJECTION",
            "android.permission.READ_PRINT_SERVICES",
            "android.permission.TRUST_LISTENER",
            "android.permission.MANAGE_APP_OPS_MODES",
            "android.permission.CONTROL_DISPLAY_SATURATION",
            "android.permission.READ_FRAME_BUFFER",
            "android.permission.TABLET_MODE",
            "android.permission.INSTALL_PACKAGES",
            "android.permission.SET_PREFERRED_APPLICATIONS",
            "android.permission.WRITE_SETTINGS",
            "android.permission.ACCESS_AMBIENT_LIGHT_STATS",
            "android.permission.BIND_DEVICE_ADMIN",
            "android.permission.MANAGE_NETWORK_POLICY",
            "android.permission.NETWORK_STACK",
            "android.permission.REVOKE_RUNTIME_PERMISSIONS",
            "android.permission.BRIGHTNESS_SLIDER_USAGE",
            "android.permission.CONTROL_DISPLAY_BRIGHTNESS",
            "android.permission.READ_WIFI_CREDENTIAL",
            "android.permission.ACCESS_MTP",
            "android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS",
            "android.permission.MANAGE_VOICE_KEYPHRASES",
            "android.permission.READ_LOGS",
            "android.permission.LOCATION_HARDWARE",
            "android.permission.INJECT_EVENTS",
            "android.permission.INTERACT_ACROSS_USERS",
            "android.permission.GRANT_RUNTIME_PERMISSIONS",
            "android.permission.ACCESS_KEYGUARD_SECURE_STORAGE",
            "android.permission.CONTROL_VPN",
            "android.permission.READ_PRINT_SERVICE_RECOMMENDATIONS",
            "android.permission.UPDATE_APP_OPS_STATS",
            "android.permission.SET_TIME_ZONE",
            "android.permission.MANAGE_IPSEC_TUNNELS",
            "android.permission.SET_ANIMATION_SCALE",
            "android.permission.SET_TIME",
            "android.permission.STORAGE_INTERNAL",
            "android.permission.DEVICE_POWER",
            "android.permission.CRYPT_KEEPER",
            "android.permission.MANAGE_USB",
            "android.permission.QUERY_DO_NOT_ASK_CREDENTIALS_ON_BOOT",
            "android.permission.READ_PRIVILEGED_PHONE_STATE",
            "android.permission.READ_NETWORK_USAGE_HISTORY",
            "android.permission.CREATE_USERS",
            "android.permission.MODIFY_PHONE_STATE",
            "android.permission.CONTROL_LOCATION_UPDATES",
            "android.permission.SET_HARMFUL_APP_WARNINGS",
            "android.permission.FREEZE_SCREEN",
            "android.permission.RESET_SHORTCUT_MANAGER_THROTTLING",
            "android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST",
            "android.permission.NETWORK_SETTINGS",
            "android.permission.DISABLE_INPUT_DEVICE",
            "android.permission.CONNECTIVITY_INTERNAL",
            "android.permission.CONFIGURE_WIFI_DISPLAY",
            "android.permission.BATTERY_STATS",
            "android.permission.MANAGE_APP_TOKENS",
            "android.permission.SET_ORIENTATION",
            "android.permission.STATUS_BAR_SERVICE",
            "android.permission.CONFIGURE_DISPLAY_COLOR_MODE",
            "android.permission.RETRIEVE_WINDOW_TOKEN",
            "android.permission.UPDATE_DEVICE_STATS",
            "android.permission.SET_POINTER_SPEED",
            "android.permission.USER_ACTIVITY",
            "android.permission.INTERACT_ACROSS_USERS_FULL",
            "android.permission.PACKAGE_USAGE_STATS",
            "android.permission.MANAGE_USERS",
            "android.permission.FILTER_EVENTS",
            "android.permission.CONFIGURE_DISPLAY_BRIGHTNESS",
            "android.permission.SET_ACTIVITY_WATCHER",
            "android.permission.CHANGE_APP_IDLE_STATE",
            "android.permission.CALL_PRIVILEGED",
            "android.permission.ACCESS_NOTIFICATIONS",
            "android.permission.ACCESS_INSTANT_APPS",
            "android.permission.MOUNT_UNMOUNT_FILESYSTEMS",
            "android.permission.ACCESS_VR_MANAGER",
            "android.permission.MANAGE_DEVICE_ADMINS",
            "android.permission.ACCESS_VOICE_INTERACTION_SERVICE",
            "android.permission.PACKAGE_VERIFICATION_AGENT",
            "android.permission.STATUS_BAR",
            "android.permission.WRITE_SECURE_SETTINGS",
            "android.permission.DELETE_PACKAGES",
            "android.permission.MOUNT_FORMAT_FILESYSTEMS",
            "android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS",
            "android.permission.OBSERVE_APP_USAGE",
            "android.permission.MOVE_PACKAGE",
            "android.permission.REBOOT",
            "android.permission.FORCE_STOP_PACKAGES",
            "android.permission.READ_DREAM_STATE",
            "android.permission.WRITE_DREAM_STATE",
            "android.permission.DUMP",
            "android.permission.REMOVE_TASKS",
            "android.permission.MANAGE_ACTIVITY_STACKS",
            "android.permission.ACCESS_VR_STATE",
            "android.permission.KILL_UID",
            "android.permission.SHUTDOWN",
            "android.permission.CLEAR_APP_GRANTED_URI_PERMISSIONS",
            "android.permission.SET_ALWAYS_FINISH",
            "android.permission.SET_DEBUG_APP",
            "android.permission.SET_SCREEN_COMPATIBILITY",
            "android.permission.STOP_APP_SWITCHES",
            "android.permission.INTERNAL_SYSTEM_WINDOW",
            "android.permission.FORCE_BACK",
            "android.permission.BACKUP",
            "android.permission.UPDATE_LOCK_TASK_PACKAGES",
            "android.permission.GET_APP_GRANTED_URI_PERMISSIONS",
            "android.permission.GET_TOP_ACTIVITY_INFO",
            "android.permission.SET_PROCESS_LIMIT",
            "android.permission.CONFIRM_FULL_BACKUP",
            "android.permission.MANAGE_FINGERPRINT" ,
            "android.permission.CLEAR_APP_CACHE" ,
            "android.permission.TEMPORARY_ENABLE_ACCESSIBILITY",
    };
    public static HashSet<String> systemPermissions = new HashSet<>(Arrays.asList(systemPermissionArray));

}
